categories:
  - title: "Features"
    semver-increment: "minor"
    when:
      label: "feature"
  - title: "Bug Fixes"
    semver-increment: "patch"
    when:
      label: "fix"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      label: "major"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      label: "fix"
