[tox]
envlist = py313, py314, lint, mypy
skip_missing_interpreters = True

[gh-actions]
python =
  3.13: py313
  3.14: py314, lint, mypy

[testenv]
extras = test
commands =
  pytest {posargs}
deps =
  pytest
  pytest-cov
  pytest-timeout
  pytest-asyncio
  requests-mock
  aioresponses
  aiofiles
  backoff

[testenv:lint]
basepython = python3
deps =
  ruff
commands =
  ruff check .
  ruff format --check .

[testenv:mypy]
basepython = python3
deps =
  mypy
  aiofiles
  types-requests
commands =
  mypy py_gasbuddy
